sudo: false
language: node_js
node_js:
  - "6.10"
cache:
  directories:
  - node_modules
script:
  - npm run test-backend
  - |
     if [ `git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep '^frontend/'` ]; then
      npm run test-frontend
     fi
  - echo $TRAVIS_COMMIT_RANGE
